version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - JWT_SECRET_KEY=your_jwt_secret_key
      - CORS_ORIGINS=["http://localhost:5173"]
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules # Prevent local node_modules from overwriting container's
    depends_on:
      - backend
    command: npm run dev

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"

volumes:
  postgres_data:
